# Generated by Django 4.1.6 on 2023-02-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_createacion_tabla_Categorias_platos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platosmodel',
            table='platos',
        ),
    ]
