"""agregamos campo estado

Revision ID: 986dcfc4bdca
Revises: 9dd1a886c246
Create Date: 2023-01-21 20:28:52.937809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986dcfc4bdca'
down_revision = '9dd1a886c246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('prodcutos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prodcutos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
